apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: fleet-management-system
build:
  artifacts:
  - image: fms-client
    context: client
    docker:
      dockerfile: Dockerfile
  - image: fms-server
    context: server
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/mongo.yaml
    - kubernetes-manifests/server.yaml
    - kubernetes-manifests/client.yaml
