apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: fleet-management-system
build:
  artifacts:
  - image: gcr.io/fleet-management-system-ets/client
    context: client
    kaniko:
      cleanup: true
  - image: gcr.io/fleet-management-system-ets/server
    context: server
    kaniko:
      cleanup: true
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/mongo.yaml
    - kubernetes-manifests/server.yaml
    - kubernetes-manifests/client.yaml
