apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2G
  hostPath:
    path: /tmp/mongo-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2G
  storageClassName: ""
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
    tier: db
spec:
  containers:
    - name: mongodb
      image: mongo:4.4.6
      ports:
        - containerPort: 27017
          name: mongodb-port
      volumeMounts:
      - name: mongo-volume
        mountPath: /data/db
  volumes:
  - name: mongo-volume
    persistentVolumeClaim:
      claimName: mongo-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    app: mongodb
  type: ClusterIP
