apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
    tier: db
spec:
  containers:
    - name: mongodb
      image: mongo:4.4.6
      ports:
        - containerPort: 27017
          name: mongodb-port
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  ports:
    - port: 27016
      protocol: TCP
  selector:
    app: mongodb
  type: ClusterIP
