apiVersion: v1
kind: Service
metadata:
  name: fms-server-service
spec:
  ports:
    - port: 8080
      targetPort: server-port
      protocol: TCP
  selector:
      app: fms-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fms-server-deployment
spec:
  replicas: 2
  template:
    metadata:
      name: fms-server
      labels:
        app: fms-server
        tier: backend
    spec:
      containers:
        - name: fms-server
          image: fms-server:1.0 #"gcr.io/fleet-management-system/server:1.0"
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: server-port
      readinessProbe:
        httpGet:
          path: /api/health
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /api/health
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 60
  selector:
    matchLabels:
      app: fms-server
  

